"""RAG algorithm parameters"""
DATA_PATH: 'data/'
DATA_SET: 'bilgeyucel/seven-wonders'
EMBEDDINGS: 'sentence-transformers/all-MiniLM-L6-v2'
LLM_MODEL: 'gpt-3.5-turbo'
PIPELINE_PATH: './_media/pipeline.png'
# 'dense'  - sentence transformers model
# 'sparse' - bm25
# 'hybrid' - both of dense and sparse
TYPE_RETRIEVAL: 'sparse'
