# """RAG algorithm parameters"""
DATA_PATH: 'data/'
DATA_SET: 'bilgeyucel/seven-wonders'
# dense - 'sentence-transformers/all-MiniLM-L6-v2'
# hybrid - "BAAI/bge-small-en-v1.5"
EMBEDDINGS: 'sentence-transformers/all-MiniLM-L6-v2'
CROSS_ENC: "BAAI/bge-small-en-v1.5"
LLM_MODEL: 'gpt-3.5-turbo'
PIPELINE_PATH: './_media/pipeline.png'
# 'dense'-sentence transformers model
# 'sparse'-bm25
# 'hybrid'-both of dense and sparse
TYPE_RETRIEVAL: 'hybrid'
