# """RAG algorithm parameters"""
DATA_PATH: 'data/'
DATA_SET: 'bilgeyucel/seven-wonders'
# dense - 'sentence-transformers/all-MiniLM-L6-v2'
# hybrid - "BAAI/bge-small-en-v1.5"
EMBEDDINGS: 'sentence-transformers/all-MiniLM-L6-v2'
CROSS_ENC: "BAAI/bge-small-en-v1.5"
# openai - gpt models as 'gpt-3.5-turbo', etc.
# huggface - 'meta-llama/Llama-2-7b-chat-hf'
#          - TinyLlama 'TinyLlama-1.1B-Chat-v1.0'
#            "mistralai/Mixtral-8x7B-Instruct-v0.1"
LLM_MODEL: 'HuggingFaceH4/zephyr-7b-beta'
# openai - openai as gpt models
# 'opensource' - opensource as llama family of models loaded from huggingface
LLM_TYPE: 'opensource'
PIPELINE_PATH: './_media/pipeline.png'
# 'dense'-sentence transformers model
# 'sparse'-bm25
# 'hybrid'-both of dense and sparse
TYPE_RETRIEVAL: 'hybrid'
